# Generated by Django 6.0.5 on 2026-06-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_user_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
