# Generated by Django 6.0.5 on 2026-06-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.profile')),
                ('follows_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='blog.profile')),
            ],
        ),
    ]
